modLoader="javafml"
loaderVersion="[32,)"
license="https://github.com/minecraftabnormals/Abnormals-Core/blob/master/LICENSE.txt"
issueTrackerURL="https://github.com/minecraftabnormals/Abnormals-Core/issues"

[[mods]]
    logoFile="logo.png"
    modId="abnormals_core"
    version="2.0.2"
    authors="Minecraft Abnormals"
    credits="SmellyModder (Luke Tonon) (code), bageldotjpg (code), and Jackson (curse page)"
    displayName="Abnormals Core"
    description='''Library mod for all Abnormals mods.'''

[[dependencies.abnormals_core]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.72,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.abnormals_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"