modLoader="javafml"
loaderVersion="[31,)"
#logoFile="abnormalscore.png"

[[mods]]
modId="abnormals_core"
version="1.0.0"
authors="Minecraft Abnormals"
credits="SmellyModder (Luke Tonon) & bageldotjpg"
displayName="Abnormals Core"
description='''Library mod for all Abnormals mods.'''

[[dependencies.abnormals_core]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.abnormals_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"