modLoader="javafml"
loaderVersion="[32,)"
license="https://github.com/team-abnormals/abnormals-core/blob/main/LICENSE.txt"
issueTrackerURL="https://github.com/team-abnormals/abnormals-core/issues"

[[mods]]
    logoFile="abnormals_core.png"
    modId="abnormals_core"
    version="3.0.0"
    authors="Minecraft Abnormals"
    credits="SmellyModder (Luke Tonon) (code), bageldotjpg (code), and Jackson (curse page)"
    displayName="Abnormals Core"
    description='''Library mod for all Abnormals mods.'''

[[dependencies.abnormals_core]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.42,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.abnormals_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"