modLoader="javafml"
loaderVersion="[32,)"
#logoFile="abnormalscore.png"
license="https://github.com/minecraftabnormals/Abnormals-Core/blob/master/LICENSE.txt"

[[mods]]
logoFile="logo.png"
modId="abnormals_core"
version="2.1.0"
authors="Minecraft Abnormals"
credits="SmellyModder (Luke Tonon) (code), bageldotjpg (code), and Jackson (curse page)"
displayName="Abnormals Core"
description='''Library mod for all Abnormals mods.'''

[[dependencies.abnormals_core]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.92,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.abnormals_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"