modLoader="javafml"
loaderVersion="[31,)"
#logoFile="abnormalscore.png"

[[mods]]
logoFile="logo.png"
modId="abnormals_core"
version="1.0.4"
authors="Minecraft Abnormals"
credits="SmellyModder (Luke Tonon) (code), bageldotjpg (code), and Jackson (curse page)"
displayName="Abnormals Core"
description='''Library mod for all Abnormals mods.'''

[[dependencies.abnormals_core]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.abnormals_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"